### ISSUE TITLE
matebook 2020 amd, ppi 102/200

### ISSUE THREAD

**Issue by pooh2pooh** [nekr0z/linux-on-huawei-matebook-13-2019#32]
Hi! The density of pixels per inch on my macbook 13 2020 amd 102. It is stated in the characteristics of 200. Free AMD GPU driver problem?
![image](https://user-images.githubusercontent.com/21198356/105021225-5afc3780-5a59-11eb-82c0-b16cbc9c9b84.png)

**Comment by nekr0z** [comment]
Maybe, no idea. The value of 102 ppi you're getting is likely wrong, because (as it says just above it on your screenshot) at this resolution it would mean that you screen is 537 mm wide. I've never seen a 2020 Matebook 13 in person, but I seriously doubt they fit a 537 mm wide screen into a 286 mm wide laptop...

**Comment by kar200** [comment]
EDIT: The screen size seems different. Is your laptop a 13"?

For me it is shwoing 144 (changed the scaling factor). I have a matebook 2020 with intel and KDE but with a 1.5 scaling factor.
Not sure if that helps.

![Screenshot_20210127_111343](https://user-images.githubusercontent.com/67429268/105956115-c1eca280-6090-11eb-8136-71fc20cbbf9a.png)

**Comment by pooh2pooh** [comment]
Yes, Matebook 13 2020 AMD + KDE. 
![image](https://user-images.githubusercontent.com/21198356/106623646-e4495900-6585-11eb-9739-159ab526825c.png)
![image](https://user-images.githubusercontent.com/21198356/106624301-908b3f80-6586-11eb-86f3-4d866acb8fdd.png)
